# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1knxmvms06VwdpmK4O8MLHUH2RW5A5Y0D
"""

import streamlit as st
import cv2
import numpy as np
import pickle
import mediapipe as mp

from PIL import Image

from mediapipe.tasks import python
from mediapipe.tasks.python import vision

# -------------------------
# Page Config
# -------------------------

st.set_page_config(
    page_title="PostureAI",
    page_icon="🧍",
    layout="centered"
)

# -------------------------
# Custom CSS
# -------------------------

st.markdown("""
<style>

.main {
    padding-top: 2rem;
}

.result-good {
    background-color: #d1fae5;
    padding: 15px;
    border-radius: 10px;
    color: black;
}

.result-bad {
    background-color: #fee2e2;
    padding: 15px;
    border-radius: 10px;
    color: black;
}

</style>
""", unsafe_allow_html=True)

# -------------------------
# Load Model
# -------------------------

@st.cache_resource
def load_model():
    with open("posture_model.pkl", "rb") as f:
        return pickle.load(f)

model = load_model()

# -------------------------
# Load Pose Detector
# -------------------------

base_options = python.BaseOptions(
    model_asset_path="pose_landmarker.task"
)

options = vision.PoseLandmarkerOptions(
    base_options=base_options,
    output_segmentation_masks=False
)

detector = vision.PoseLandmarker.create_from_options(
    options
)

# -------------------------
# Header
# -------------------------

st.title("🧍 AI Posture Detection System")

st.write(
    "Upload an image and detect whether posture is Good or Bad using MediaPipe and Machine Learning."
)

# -------------------------
# Upload Image
# -------------------------

uploaded_file = st.file_uploader(
    "Upload Posture Image",
    type=["jpg", "jpeg", "png"]
)

if uploaded_file:

    image = Image.open(uploaded_file)

    st.image(
        image,
        caption="Uploaded Image",
        use_container_width=True
    )

    if st.button("Analyze Posture"):

        img = np.array(image)

        if len(img.shape) == 2:
            img = cv2.cvtColor(
                img,
                cv2.COLOR_GRAY2RGB
            )

        rgb = img.copy()

        mp_image = mp.Image(
            image_format=mp.ImageFormat.SRGB,
            data=rgb
        )

        result = detector.detect(
            mp_image
        )

        if len(result.pose_landmarks) == 0:

            st.error(
                "No person detected in image."
            )

        else:

            features = []

            for lm in result.pose_landmarks[0]:

                features.extend([
                    lm.x,
                    lm.y,
                    lm.z
                ])

            prediction = model.predict(
                [features]
            )[0]

            confidence = model.predict_proba(
                [features]
            )

            conf = float(
                np.max(confidence)
            ) * 100

            # -------------------------
            # GOOD
            # -------------------------

            if prediction == "good":

                st.markdown(
                    f"""
                    <div class="result-good">
                    <h2>✅ Good Posture</h2>
                    <h4>Confidence: {conf:.2f}%</h4>
                    </div>
                    """,
                    unsafe_allow_html=True
                )

                st.success(
                    "Great posture! Keep maintaining proper alignment."
                )

            # -------------------------
            # BAD
            # -------------------------

            else:

                st.markdown(
                    f"""
                    <div class="result-bad">
                    <h2>⚠️ Bad Posture</h2>
                    <h4>Confidence: {conf:.2f}%</h4>
                    </div>
                    """,
                    unsafe_allow_html=True
                )

                st.warning(
                    "Try keeping shoulders back and neck straight."
                )

                st.markdown("""
### Tips to Improve Posture

- Sit upright
- Keep shoulders relaxed
- Avoid bending neck forward
- Keep monitor at eye level
- Take regular stretch breaks
""")